title: "Dev Env Party 🎉"
description: "Get in-person help setting up your computer with Node.js, npm, & Git!"
permalink: /posts/:title
baseurl: ''
exclude: [node_modules, tmp, bin, README.md]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
